version: 2

sources:
  - name: erp
    description: Fonte SAP de vendas da Northwind
    schema: erp_northwind
    tables:
      - name: products
        colums:
          - name: prodcut_id
            tests:
            - unique
            - not_null
                    
      - name: categories
      - name: suppliers
      
